### ISSUE TITLE
Enklare README

### ISSUE THREAD

**Issue by gurkor112** [kryptokrona/kryptokrona#5]
För att lättare hitta allting föreslår jag att ändra i README filen så att kryptokrona-service executable är en länk och pekar mot https://github.com/kryptokrona/kryptokrona/releases.

Dvs:

You will also need to place the appropriate 
[kryptokrona-service executable](https://github.com/kryptokrona/kryptokrona/releases)
 for your OS in the /bin/-folder of the project.

Istället för:

You will also need to place the appropriate kryptokrona-service executable for your OS in the /bin/-folder of the project.

**Comment by f-r00t** [comment]
Tack för feedbacken, men du kanske menade att posta detta i Hugin Messenger repot? https://github.com/kryptokrona/hugin-messenger

**Comment by gurkor112** [comment]
Ja det stämmer, hamnade lite fel

**Comment by gurkor112** [comment]
Postade det på rätt ställe nu, tack!
