### ISSUE TITLE
Add STUN server 

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona#77]
Implement STUN Server with Rust and link it to CMake build system.

**Comment by f-r00t** [comment]
Or you could just add the stun server alongside the Hugin API and the node in the Hugin full node recipe.
Here's a guide on how to run a STUN-server with coturn:
https://ourcodeworld.com/articles/read/1175/how-to-create-and-configure-your-own-stun-turn-server-with-coturn-in-ubuntu-18-04

**Comment by mjovanc** [comment]
@TechyGuy17 Can you set this up using Ansible? Just add a conf file for it and set it up. Add iptables rules for opening the ports up etc. 

```Dockerfile
FROM coturn/coturn

# Copy your custom configuration file
COPY turnserver.conf /etc/turnserver.conf

# Expose ports for STUN and TURN protocols
EXPOSE 3478 5349

# Start the STUN server
CMD ["/usr/bin/turnserver"]
```

**Comment by TechyGuy17** [comment]
Done. can someone mark as complete?
